### ISSUE TITLE
question about the covariates file

### ISSUE THREAD

**Issue by kaibios0101** [YangLabHKUST/XPASS#2]
Dear mxcai, 

Thanks for your powerful method for trans-ancestry PRS analysis. I ran into a problem when applying the XPASS method. 

In your manual, you noted that the covariates files, which only contain PCs information, for the reference panels are optimal. When using the same data and code in our manual, I could replicate these results presented in the manual. However,  if the covariates files were not used in the XPASS function, an impossible genetic correlation value was generated, as showed below:

              h1                 h2                h12             rho
[1,] 0.072180463 0.15389606 0.124566236 1.18188918
[2,] 0.003322473 0.00530962 0.006599995 0.03706045

Do you have the same problem, or maybe I miss some important information? 

Bests,

Kai

**Comment by mxcai** [comment]
Hi Kai,

Thank you for your interest in XPASS. 

While the covariates files are optional in the XPASS software, it is very important to include PCs as covariates. This is because XPASS utilizes the LD from the entire genomes to estimate the heritability and coheritability. Without including PCs, the population stratification in the reference genotypes can bias the parameter estimates (see https://github.com/YangLabHKUST/XPASS/blob/master/ref_cvt.pdf for discussion). This is why the estimated genetic correlation exceeds 1. Therefore, we strongly suggest users to include genotype PCs and other covariates such as sex and age when available.

Best,
Mingxuan

**Comment by kaibios0101** [comment]
Hi Mingxuan,

Thanks for your detailed explanation. I have no further problems with this issue. By the way, as you stated that "XPASS utilizes the LD from the entire genomes to estimate the heritability and coheritability", could you kindly provide the referenced paper for me?  

Besides, I have another problem.  In your manual, these reference panels only contain 377 EAS samples and 417 EUR samples from the 1000 Genomes project. However, we know that 504 EAS samples and 503 EUR samples in the 1000 Genomes project.  Could you explain the difference in sample size, or by what criteria did you throw away some samples?

Bests, 

Kai

**Comment by mxcai** [comment]
For parameter estimation, we followed the MQS framework, which yields smaller standard error than LDSC. The MQS paper can be found at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5836736/. 

For the 1000 Genomes reference panel, we used the phase 3 plink files provided by the Alkes Price's group in https://alkesgroup.broadinstitute.org/LDSCORE/, and further removed relatives by using --rel-cutoff 0.025 in plink command. Please note that we used the One Thousand Genomes genotypes only for demonstration because they are accessible by everyone. In practice, we found large sample size (>=2000) usually offers stable improvement of prediction accuracy. 

Best,
Mingxuan

**Comment by kaibios0101** [comment]
Hi Mingxuan,

Thanks for your patient explanation. I have no further questions. Many thanks!

Bests, 

Kai
