### ISSUE TITLE
Question about the predictive R2

### ISSUE THREAD

**Issue by kaibios0101** [YangLabHKUST/XPASS#3]
Hi Mingxuan,

I found a large difference between the predictive R2 of BMI reported in your paper (max R2: 5.97%) and in the manual (max R2: 3.29%).  In your paper, you used the 2,000 individuals from both UKBB and the Chinese dataset as the LD reference panels for the two populations, and about ~4M SNPs to construct the PRS. However, in the manual, only 377 EAS samples and 417 EUR samples from 1KG, and ~1.3M SNPs from HapMap3 were used to construct the PRS.  Is the inconsistency of predictive R2 due to the different sample sizes of the LD reference panel or the different number of SNPs?

If the predictive R2 is mainly affected by the sample sizes of the LD reference panel, could you provide a reference panel of the UKB data and corresponding covariates file? Since the UKB data is not easily accessible, both due to the limited application and the difficulty in data storage and computation, a reference panel based on UKB will promote the applicability of the XPASS method.

Bests, 

Kai

**Comment by mxcai** [comment]
Hi Kai,

Thanks for raising the question. Both reference sample size and SNPs can influence the prediction accuracy. Based on our analysis with individual-level data, where the reference panel is not required, we found higher predictive R2 with the inclusion of all 3 million SNPs rather than only 1.3 million SNPs in HapMap 3. Therefore, we believe that the discrepancy in the BMI example mainly comes from the different SNPs included in the model.

We are sorry but we are not able to provide UKBB reference data because of the data accession policy. We suggest users to use their own reference panels with larger sample size in analysis when available.

Best,
Mingxuan

**Comment by kaibios0101** [comment]
Hi Mingxuan,

Thanks for your explanation. 

Bests, 

Kai
